//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bucket.manager.wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bucket.manager.wpf.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string btnAuthenticate {
            get {
                return ResourceManager.GetString("btnAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bucket.
        /// </summary>
        public static string btnCreateBucket {
            get {
                return ResourceManager.GetString("btnCreateBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Object.
        /// </summary>
        public static string btnDeleteObject {
            get {
                return ResourceManager.GetString("btnDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevTools.
        /// </summary>
        public static string btnDevTools {
            get {
                return ResourceManager.GetString("btnDevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download SVF.
        /// </summary>
        public static string btnDownloadSVF {
            get {
                return ResourceManager.GetString("btnDownloadSVF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JavaScript.
        /// </summary>
        public static string btnJavaScript {
            get {
                return ResourceManager.GetString("btnJavaScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Buckets.
        /// </summary>
        public static string btnRefreshBuckets {
            get {
                return ResourceManager.GetString("btnRefreshBuckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate File.
        /// </summary>
        public static string btnTranslateFile {
            get {
                return ResourceManager.GetString("btnTranslateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string btnUploadFile {
            get {
                return ResourceManager.GetString("btnUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMEA.
        /// </summary>
        public static string cbItemEMEA {
            get {
                return ResourceManager.GetString("cbItemEMEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US.
        /// </summary>
        public static string cbItemUS {
            get {
                return ResourceManager.GetString("cbItemUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Failed to call APS services.
        /// </summary>
        public static string errGeneral {
            get {
                return ResourceManager.GetString("errGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Missing Application Credentials!.
        /// </summary>
        public static string errMissingCredentials {
            get {
                return ResourceManager.GetString("errMissingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket only can be named with -_.a-z0-9 and length between 3-128 characters..
        /// </summary>
        public static string errorBucketName {
            get {
                return ResourceManager.GetString("errorBucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error .
        /// </summary>
        public static string errorCaption {
            get {
                return ResourceManager.GetString("errorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Can&apos;t download resource .
        /// </summary>
        public static string errorDownloading {
            get {
                return ResourceManager.GetString("errorDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Not authenticated, please authenticate first..
        /// </summary>
        public static string errorNotAuthenticate {
            get {
                return ResourceManager.GetString("errorNotAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects required.
        /// </summary>
        public static string errorObjectSelectionCaption {
            get {
                return ResourceManager.GetString("errorObjectSelectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an object.
        /// </summary>
        public static string errorObjectSelectionMessage {
            get {
                return ResourceManager.GetString("errorObjectSelectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Translation timeout(6 minutes).
        /// </summary>
        public static string errorTranslateTimeout {
            get {
                return ResourceManager.GetString("errorTranslateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket required.
        /// </summary>
        public static string errorUploadCaption {
            get {
                return ResourceManager.GetString("errorUploadCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a bucket.
        /// </summary>
        public static string errorUploadMessage {
            get {
                return ResourceManager.GetString("errorUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        public static string errSuffix {
            get {
                return ResourceManager.GetString("errSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token:.
        /// </summary>
        public static string lblAccessToken {
            get {
                return ResourceManager.GetString("lblAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add GUID as suffix?.
        /// </summary>
        public static string lblAddGUID {
            get {
                return ResourceManager.GetString("lblAddGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Credentials.
        /// </summary>
        public static string lblAPSCredential {
            get {
                return ResourceManager.GetString("lblAPSCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bucket.
        /// </summary>
        public static string lblCreateBucket {
            get {
                return ResourceManager.GetString("lblCreateBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your bucket name here:.
        /// </summary>
        public static string lblCreateBucketName {
            get {
                return ResourceManager.GetString("lblCreateBucketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monaco editor(VSCode).
        /// </summary>
        public static string lblMonacoEditor {
            get {
                return ResourceManager.GetString("lblMonacoEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region:.
        /// </summary>
        public static string lblRegion {
            get {
                return ResourceManager.GetString("lblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret:.
        /// </summary>
        public static string lblSecret {
            get {
                return ResourceManager.GetString("lblSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket Manager.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  will be permantly delete, confirm?.
        /// </summary>
        public static string msgDeleteConfirm {
            get {
                return ResourceManager.GetString("msgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string msgDeleteConfirmCaption {
            get {
                return ResourceManager.GetString("msgDeleteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save before exit?.
        /// </summary>
        public static string msgSaveBeforeExit {
            get {
                return ResourceManager.GetString("msgSaveBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        public static string msgSaveCaption {
            get {
                return ResourceManager.GetString("msgSaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating....
        /// </summary>
        public static string statusAuthenticating {
            get {
                return ResourceManager.GetString("statusAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting item: .
        /// </summary>
        public static string statusDelete {
            get {
                return ResourceManager.GetString("statusDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting extraction....
        /// </summary>
        public static string statusDownloading {
            get {
                return ResourceManager.GetString("statusDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading .
        /// </summary>
        public static string statusDownloadingFile {
            get {
                return ResourceManager.GetString("statusDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mbs uploaded....
        /// </summary>
        public static string statusMbsUploaded {
            get {
                return ResourceManager.GetString("statusMbsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing to upload file....
        /// </summary>
        public static string statusPreparingUpload {
            get {
                return ResourceManager.GetString("statusPreparingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string statusReady {
            get {
                return ResourceManager.GetString("statusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Bucket:.
        /// </summary>
        public static string statusRefreshingBucketItems {
            get {
                return ResourceManager.GetString("statusRefreshingBucketItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing Buckets....
        /// </summary>
        public static string statusRefreshingBuckets {
            get {
                return ResourceManager.GetString("statusRefreshingBuckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation in progress....
        /// </summary>
        public static string statusTranslating {
            get {
                return ResourceManager.GetString("statusTranslating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        public static string statusUploading {
            get {
                return ResourceManager.GetString("statusUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click to view translated model.
        /// </summary>
        public static string tooltipBucketTree {
            get {
                return ResourceManager.GetString("tooltipBucketTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your Application Client ID here.
        /// </summary>
        public static string tooltipID {
            get {
                return ResourceManager.GetString("tooltipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your Application Client Secret here.
        /// </summary>
        public static string tooltipSecret {
            get {
                return ResourceManager.GetString("tooltipSecret", resourceCulture);
            }
        }
    }
}
